# 应用名称
server:
  port: 8080
#spring:
#
#  application:
#
#    name: nacos-consumer
#
#  cloud:
#
#    # nacos服务地址
#
#    nacos:
#
#      server-addr: 127.0.0.1:8848
#      discovery:
#        server-addr: 127.0.0.1:8848

