# 应用名称
server:
  port: 8086
#spring:
#
#  application:
#
#    name: nacos-provider
#
#  cloud:
#
#    # nacos服务地址
#
#    nacos:
#
#      server-addr: 127.0.0.1:8848
#      config:
#        name: nacos-provider